[build]
  publish = "dist/"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "@netlify-plugin-image-optim"
[[plugins]]
  package = "@netlify-plugin-inline-critical-css"


[build.environment]
  NODE_VERSION = "18.20.2"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

